### ISSUE TITLE
cinema times by cinema

### ISSUE THREAD

**Issue by celine305** [nickcharlton/moviesapi#1]
Hi Nick, 

Your movie api is great! Is it still active? I can't seem to figure out how to use the 'cinema times by cinema' feature. For example the query below gives me an internal server error:

http://moviesapi.herokuapp.com/cinemas/:9393/showings

Could you please take a look at this?

Thanks,

Celine

**Comment by nickcharlton** [comment]
Hi!

Yes, it’s still active. It, unfortunately, looks like there’s a bug with the parsing code and so it’s throwing up a JSON error (which you can’t see).

Secondly, you shouldn’t need the “:” in the url for the cinema id.

I’ll take a look and try and get this fixed soon!

**Comment by nickcharlton** [comment]
I’ve now fixed and deployed this, it should now be working again!

**Comment by celine305** [comment]
Thank you!
