### ISSUE TITLE
Showings endpoint returns 500 error

### ISSUE THREAD

**Issue by jmcquaidMetapack** [nickcharlton/moviesapi#7]
Hi.

When I called this endpoint:
http://moviesapi.herokuapp.com/cinemas/9905/showings

I got a 500 status code.

Extra details:
I ran the app locally, and the following error appeared in the logs:

``
NoMethodError: undefined method `[]' for false:FalseClass
/Users/jmcquaid/workspace/moviesapi/lib/movies_api/find_any_film.rb:143:in `film_from_json'
``

This error was thrown because the response from:

``     
https://www.findanyfilm.com/api/screenings/by_venue_id/venue_id/9905/date_from/2018-05-13
``

contained values like:

``
"film_data": false
``

Instead of details about the film.

**Comment by nickcharlton** [comment]
Hi!

I've been seeing this in the exception handling it's using, and it seems to be related to data missing in the field.

I've figured out a fix (to skip over that record), which I'll be opening a PR for soon.

**Comment by jmcquaidMetapack** [comment]
Ok, great.
